### ISSUE TITLE
Can't run using npm run serve

### ISSUE THREAD

**Issue by itsChris** [EnviDat/EnviDat-Frontend#1]
- i cloned the repo. 
- i did a npm install

i got: 

found 35586 vulnerabilities (35554 low, 29 moderate, 3 high) -> i did not fix/audit those.

-> npm run serve results in: 

ERROR  Failed to compile with 10 errors.

basically it seems the be a repeating pattern -> You may need an additional loader to handle the result of these loaders.

You may need an additional loader to handle the result of these loaders.
|
|     bingApiKey() {
>       return this.config?.apiKeys?.bing;
|     },
|

[Here's my EnviDat-RunServeErrors.txt](https://github.com/EnviDat/EnviDat-Frontend/files/6189181/EnviDat-RunServeErrors.txt)

most probably i did something wrong. Maybe you can point me in a direction to solve this errors?

thanks - appreciate your contribution!

Christian

**Comment by DomDomHaas** [comment]
Hi Christian

Thanks for your interest and your feedback.
Yes right, the babel config is missing some entries. I've only added them in a feature branch.
I'm going to add it to the master aswell... should be fixed in around 10mins.

I'll reply again.

**Comment by DomDomHaas** [comment]
Okay done, could you try again please :)

**Comment by itsChris** [comment]
now it works like a charm, thanks!
amazing work btw!

Christian
